### ISSUE TITLE
Unnecessary error in the event handler for webRequest.onBeforeRequest

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1015]
It seems that we're trying to call `collapseElement` for the background page:
```
Error in event handler for webRequest.onBeforeRequest/1: Error: Invalid value for argument 1. Value must not be less than 0.
    at Object.adguard.tabsImpl.insertCssCode (chrome-extension://gfggjaccafhcbfogfkogggoepomehbjl/lib/api/tabs.js:450:22)
    at collapseElement (chrome-extension://gfggjaccafhcbfogfkogggoepomehbjl/lib/webrequest.js:155:22)
    at onBeforeRequest (chrome-extension://gfggjaccafhcbfogfkogggoepomehbjl/lib/webrequest.js:105:13)
    at browser.webRequest.onBeforeRequest.addListener.urls.urls (chrome-extension://gfggjaccafhcbfogfkogggoepomehbjl/lib/api/background-page.js:196:24)
```

**Comment by maximtop** [comment]
Could you tell me how to reproduce this issue, please?

**Comment by vozersky** [comment]
Would appreciate STR as well

**Comment by ameshkov** [comment]
Not that there're any so just believe us :)
